--Primeiro relatório
SELECT C.DESCRICAO, A.NOME FROM CURSO C
INNER JOIN MATRICULA M ON (M.CODCURSO = C.CODCURSO)
INNER JOIN ALUNO A ON (A.CODALUNO = M.CODALUNO)
GROUP BY 1

-- Segundo relatório
SELECT COUNT(CODMATRICULA) as QUANTIDADE, C.DESCRICAO FROM MATRICULA M
INNER JOIN CURSOS C ON (C.CODCURSO = M.CODCURSO)
GROUP BY 1
WHERE CAST(C.CODCURSO AS VARCHAR) = '%".$filtro"%' OR 


